version: '3'
services:
  app:
    build: .
    environment:
      - S3_ENDPOINT=http://localstack:4566
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - AWS_REGION=${AWS_DEFAULT_REGION:-us-east-1}
    security_opt:
      - no-new-privileges:true
    depends_on:
      localstack:
        condition: service_healthy
      dynamodb:
        condition: service_healthy
  # nosemgrep: writable-filesystem-service
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - PERSISTENCE=1
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      # for linux change to this
      # - "/var/run/docker.sock:/var/run/docker.sock"
      - "/private/var/run/docker.sock:/var/run/docker.sock"
      - "./volume/s3:/tmp/localstack/s3"
      - "./localstack-init.sh:/etc/localstack/init/ready.d/init-aws.sh"
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: "curl -s localhost:4566/_localstack/health | grep -q '\"s3\": \"available\"'"
      interval: 5s
      retries: 10
      timeout: 10s
  dynamodb:
    image: amazon/dynamodb-local:latest
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodb"
    ports:
      - "${DYNAMODB_PORT}:8000"
    volumes:
      - "./volume/dynamodb:/home/dynamodb"
    user: "1000:1000"  # ปรับตาม user:group ของระบบคุณ
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5