#!/bin/bash

# กำหนดโฟลเดอร์ที่จะเก็บไฟล์ .pem
BASE_DIR="/Users/yongyutjantaboot/WebstormProjects/brave-core-crx-packager/out-all-pem"

# รายการ ID ทั้งหมด
IDS=(
acjngemejiflkehbcbomjgkbfhjlgioh
adcocjohghhfpidemphmcmlmhnfgikei
afggnigkiebjlahlhcjgjahbhfikcipa
almolcgbkikkhliiibfjkohebgklegam
beeceepafhbchnbfdkfalfipoancnjkm
bfpgedeaaibpoidldhjcknekahbikncb
cdbbhgbmjhfnhnmgeddbliobbofkgdhe
cgmhmpbimmakidhlkcnnehhicoclofep
cjoooeeofnfjohnalnghhmdlalopplja
cpapfkpkeaajehipopnaiihfmbfbnkdp
dcfccddjfmckaigemleendolfmmaaiii
eaidcpcfnepdmmhbglgjhpjdfodkdcki
eaokkjgnlhceblfhbhpeoebmfldocmnc
fbljdmoohhbifebddjnbbljgencmpjlb
fdmemomgcgpopbhhmdkdedkphkglhopj
fejmaeodjeekfldnbegjagemjgnmhfof
femdbljnkmindcakmnbjhfefepeaicnm
flnkmpokemfpaajmiimmjeiandgoodgg
fmddkdeghohhfoglgdpkhlnfgmmffklg
gdlpebjigadbdpjpfpdbmogebilelnbh
ggjlfgjhaeedkajcdpomeidjlniafdnp
gkboaolpopklhgplhaaiboijnklogmbc
gomenlogbembmkbghmaoledggliepdef
hkeaopcnlcfbmbogejmbipnnopjlpiph
hmnnhojoekmmehfpmeegehbmifiijobb
iiglahilpgmhlcogkkihklnbcjjgpddl
iihfaghdnbilkdhmmnnkebhodfgeaopd
iodkpdagapdfkphljnddpjlldadblomo
jbjcimgbgpgbgkjalhlhgldfflklfgef
jcfckfokjmopfomnoebdkdhbhcgjfnbi
jiajbjlakknofnkmlokcbanjbajpbdkl
johkmlmpfakcaopiapbmcocgpkabdmed
kdakdkdknmkkafefhcbngpinlfoopoej
kdddfellohomdnfkdhombbddhojklibj
keclkbppmfihehggeadflldbjpolcpgf
kjdbffhfijkonelaglifggkchhmgmeli
lbnibkdpkdjnookgfeogjdanfenekmpe
ldnolaledjfkfgpjkbkcfjiaejeeanmh
lfmefmifdjlfneapckmpkinmlofjehbp
llgjaaddopeckcifdceaaadmemagkepi
meimhmgfbckapkbbbdaoefgnbppmkodp
mfddibmblmbccpadfndgakiopmmhebop
mhccgcegedfkhdbfbgllfkkcjhgkoinc
mjhbdghipcamfoojbeikdojibeelbmil
mpgdjfnjjmglioiflfioiappfbdbkeno
nbkknaieglghmocpollinelcggiehfco
ngcohbdfildjnmfnicgdipopmlhdcokg
nnpbcdahaefknppiijdmnckpdgojejck
npcnkjiaolpnapjleimicclmdcccoeme
oegebjahecghlckbhkmojgnpcgdeajdi
oimegboipnkgekgoccmlljjlhhbjaoil
olkjbfppmeijhkjhjjmfdbloighaigmh
omoaeaghhgmiojkeaemjkpkmelmalbgo
onooookdmjmijocbeafcldnbfiaobhjk
ooamlicohiiaodkaemgoimcihidbedmp
oojedkppeblkjkcdlmlahnhndjmbicoi
phdmgpanpejkbmbljlhcehpadabljfbk
phmomndefejccjmpiehbogokakkmnmgb
jdfljimmboeigmdgniclollfijpkcoaf
afalakplffnnnlkncjhbmahjfjhmlkal
eeigpngbgcognadeebkilcpcaedhellh
aoojcmojmmcbpfgoecoadbdpnagfchel
jflookgnkcckhobaglndicnbbgbonegd
nlpaeekllejnmhoonlpcefpfnpbajbpe
cldoidikboihgcjfkhdeidbpclkineef
cpoalefficncklhjfpglfiplenlpccdb
biahpgbdmdkfgndcmfiipgcebobojjkp
kkjipiepeooghlclkedllogndmohhnhi
giekcmmlnklenlaomppkphknjmnnpneh
hfnkpimlhhgieaddgfemjhofmfblmnib
ggkkehgbnfjpeggfpleeakpidbkibbmn
khaoiebndkojlmppeemjhbpbandiljpe
jamhcnnkihinmdlkakkaopbjbbcngflc
laoigpblnllgcgjnjnllmfolckpjlhki
gccbbckogglekeggclmmekihdgdpdgoe
aoojcmojmmcbpfgoecoadbdpnagfchel
oimompecagnajdejgnnjijobebaeigek
ojhpjlocmbogdgmfpkhlaaeamibhnphh
pphbpmdlkglnolofoaifgkbmkdoobalm
heplpbhjcbmiibdlchlanmdenffpiibo
jcffalbkohmmfjmgkdcphlimplejkmon
obedbbhbpmojnkanicioggnmelmoomoc
hajigopbbjhghbfimgkfmpenfkclmohk
efniojlnjndmcbiieegkicadnoecjjef
jflhchccmppkfebkiaminageehmchikm
bfdgpgibhagkpdlnjonhkabjoijopoge
ldimlcelhnjgpjjemdjokpgeeikdinbm
cffkpbalmllkdoenhmdmpbkajipdjfam
ghnjmapememheddlfgmklijahiofgkea
fnpjliiiicbbpkfihnggnmobcpppjhlj
dmoefgliihlcfplldbllllbofegmojne
llhecljkijgcaalnbfadljdpkpbehakp
hmabmnondepbfogenlfklniehjedmicd
oooemoeokehlgldpjjhcgbndjcekllim
kdcalgmhljnckmnfcboeabeepgnlaemf
jboldinnegecjonfmaahihagfahjceoj
lddghfaofadfpaajgncgkbjhalgohfkd
djhjpnilfflibdflbkgapjfldapkjcgl
njhlaafgablgnekjaodhgbaomabjibaf
fijddbnggnpidebfbejillgbopcikfpi
ekodlgldheejnlkhiceghfgdcplpeoek
oidcknjcjepjgfpammgdalpnjefekhge
abeicfkepbhgindohkebelkkhnnijcaf
cklgijeopkpaadeipkhdaodemoenlene
pmgkiiodjlmmpimpmphjhkodjnjfkeke
omkkefoeihpbpebhhbhmjekpnegokpbj
oimfmeehpinnecjghphifehbbnddjkmf
enkheaiicpeffbfgjiklngbpkilnbkoi
hjeidaaocognlgpdkfeenmiefipcffbo
lgfeompbgommiobcenmodekodmdajcal
egooomckhdgnfbpofhkbhbkiejaihdll
emaecjinaegfkoklcdafkiocjhoeilao
fbmjnabmpmfnfknjmbegjmjigmelggmf
facajiciiepdpjnoifonbfgcnlbpbieo
gpgegghiabhggiplapgdfnfcmodkccji
agfanagdjcijocanbeednbhclejcjlfo
nkmllpnhpfieajahfpfmjneipnddhimi
pdecoifadfkklajdlmndjpkhabpklldh
paoecjnjjbclkgbempaeemcbeldldlbo
dbcccdegkijbppmeaihneimbghfghkdl
llpoppgpcimnmhgehpipdmamalmpfbjd
fmcofgdkijoanfaodpdfjipdgnjbiolk
jmomcjcilfpbaaklkifaijjcnancamde
gemncmbgjgcjjepjkindgdhdilnaanlc
coofeapfgmpkchclgdphgpmfhmnplbpn
)

# สร้างไฟล์ .pem สำหรับแต่ละ ID
for id in "${IDS[@]}"; do
    pem_file="$BASE_DIR/$id.pem"
    if [ ! -f "$pem_file" ]; then
        echo "Creating.. $pem_file"
        openssl genrsa 2048 | openssl pkcs8 -topk8 -nocrypt -out "$pem_file"
        chmod 600 "$pem_file"
    else
        echo "$pem_file Existed skipping"
    fi
done

echo "Successfully"